### ISSUE TITLE
linkgopher stop working since sept 2nd at all (Firefox)

### ISSUE THREAD

**Issue by lutzd** [az0/linkgopher#48] opened 2021-09-03 12:34 UTC
thanks for quick fix.
I had trash firefox an runs developer edition. And all linkgopher works fine as expected.
two days ago my linkgopher stop working at all.
had reset to default firefox 92x64 on 1st system
have downgrade firefox 92x64 to 89x64 back
have started firefox 82x64 on ubuntu
give all permissions access/open tabs and websites of course
nothing work
version 2.2. seems to be deadhowever, the 
window "about linkgopher" didnt pop up
nor both extract windows
pls help or check if some going better

**Comment by jantje** [comment] 2021-09-03 14:02
Linkgopher stopped working for me today.
When I click the icon I get the options
![afbeelding](https://user-images.githubusercontent.com/1175841/132017435-28793c14-d0ff-4448-8a5d-72f7101c9bf0.png)

But clicking on any of the buttons does nothing
As I used Linkgopher yesterday and A new version was installed today I assume there is something wrong with the new version
![afbeelding](https://user-images.githubusercontent.com/1175841/132017907-5af2c246-7abe-4df7-b6ec-4d15dcb280c7.png)
I'm willing to do further investigation if wanted.

Thanks for the cool tool

**Comment by az0** [comment] 2021-09-03 14:18
I reverted the keyboard shortcut feature and tested with Firefox 92.0b9 (developer). It works, and I will upload to the Mozilla extension site.

Meanwhile, you can install this version. Rename from ZIP to XPI, and drag onto the Firefox extensions page. It is not digitally signed, so I had to use Firefox Developer edition to install it.

[link-gopher-2.4.4.zip](https://github.com/az0/linkgopher/files/7106495/link-gopher-2.4.4.zip)

**Comment by jantje** [comment] 2021-09-03 14:58
I tried to install it but I can't get past the "signing requirement" even after I turned the signing requirement off.
![afbeelding](https://user-images.githubusercontent.com/1175841/132025973-96d79150-aa89-431a-a492-3e3b44fe87c1.png)
![afbeelding](https://user-images.githubusercontent.com/1175841/132026058-254d9a20-1768-451d-b824-d3940ed8bd5a.png)

Sorry I can't test
Thanks for the swift response

**Comment by az0** [comment] 2021-09-03 15:12
Can you download and install the Firefox developer edition?

https://www.mozilla.org/en-US/firefox/developer/

Alternatively, you can get the new version in a few days after Mozilla
reviews and approves it


Andrew

**Comment by donmiyamar** [comment] 2021-09-03 17:42
Thanks for the quick fix @az0 !

**Comment by jantje** [comment] 2021-09-03 18:25
@az0 
I'll go for the alternative
Thanks for the quick fix.

**Comment by lutzd** [comment] 2021-09-04 15:41
Hallo
after replacing my Firefoxportable to FirefoxDeveloper Edition and additional deactivate Certification check for XPI all works fine.
Thanks all for this fine tool.
Lutz

**Comment by jantje** [comment] 2021-09-07 16:01
Works again in firefox :-)
Thanks

**Comment by az0** [comment] 2023-09-28 03:26
>Works again in firefox :-)

Closing because confirmed working

**Closed by az0** 2023-09-28 03:26 UTC
